services:
  nginx:
    image: nginx:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
