log_format cloudflare '$http_cf_connecting_ip - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    access_log /var/log/nginx/access.log cloudflare;

    location / {
        try_files $uri $uri/ =404;
    }
}
